dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.59
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.59
- name: infrastructure
  repository: file://../infrastructure
  version: 0.1.0
- name: application
  repository: file://../application
  version: 0.1.0
- name: activiti-cloud-query
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.22
