dependencies:
- name: example-runtime-bundle
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.1
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.59
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.59
