dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.59
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.59
- name: infrastructure
  repository: file://../infrastructure
  version: 0.1.0
- name: application
  repository: file://../application
  version: 0.1.0
- name: activiti-cloud-query
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.28
- name: activiti-cloud-demo-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.37
- name: activiti-cloud-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.51
- name: example-runtime-bundle
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.43
- name: iron-mountain-activiti-7-poc
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.7
- name: activiti-cloud-audit
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.13
